server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #配置Nacos地址
        server-addr: 192.168.1.20:1111   # ip:port 配置nacos的集群地址

#端口暴漏
management:
  endpoints:
    web:
      exposure:
        include: '*'
